### ISSUE TITLE
errors in find_sets.py

### ISSUE THREAD

**Issue by wqhf** [raphael-group/weighted-exclusivity-test#34]
Hello,

The example provided by your team is ok. When I test my own data, I met errors in `find_sets.py`. I don't know how to solve it so that I paste my script and the log file here. Please give some suggestions. Thank you!

```shell
(venv) [xxx@xxx wext]$ python /data2/database/opt/common/wext/wext-1.3.0/find_sets.py -mf data/mutation.exonic.json -wf weights.npy  -s  exclusivity -k 2 -c  $num_cores -f  2 -o  exclusivity_results  -v  1
```
```
------------------------------ Input Mutation Data -----------------------------
- Genes: 6249
- Patients: 43
- Genes mutated in >=2 patients: 2028
------------------------------- Enumerating Sets -------------------------------
k=2: 2055378 sets...
- Output 2042825 sets
	Removed 12553 sets with NaN or invalid P-values
	Ignored 0 sets with Z >= T or a gene with no exclusive mutations
Traceback (most recent call last):
  File "/data2/database/opt/common/wext/wext-1.3.0/find_sets.py", line 158, in <module>
    if __name__ == '__main__': run( get_parser().parse_args(sys.argv[1:]) )
  File "/data2/database/opt/common/wext/wext-1.3.0/find_sets.py", line 156, in run
    output_enumeration_table( args, k, setToPval, setToRuntime, setToFDR, setToObs, args.fdr_threshold )
  File "/data2/database/opt/common/wext/wext-1.3.0/wext/i_o.py", line 66, in output_enumeration_table
    k = len(rows[0][0].split(', '))
IndexError: list index out of range
```

**Comment by Sames-Jtudd** [comment]
I have the same issue. Any suggestions would be appreciated

**Comment by Sames-Jtudd** [comment]
Increasing the number of genes in the set 'solved' the problem
